#define _CRT_SECURE_NO_WARNINGS

//#define BRACKET_NEWLINE

#include <stdio.h>
#include <stdbool.h>
#include <malloc.h>
#include <stdint.h>

#ifdef BRACKET_NEWLINE
#define BRACKET_NEWLINE "\n"
#else // BRACKET_NEWLINE
#define BRACKET_NEWLINE " "
#endif // BRACKET_NEWLINE


#define FREQINDEX_TYPE char
#define MAX_FREQCOUNT sizeof(FREQINDEX_TYPE) << 8

#define TIMEINDEX_TYPE char
#define MAX_TIMECOUNT sizeof(TIMEINDEX_TYPE) << 8

#define _STR(s) #s
#define STR(s) _STR(s)

static void printNumbers(FILE *pf, const char *format, int blanksize, size_t numperline, const void *data, size_t datacount, size_t datasize) {
	for (size_t i = 0; i < datacount; i++) {
		if (i % numperline == 0) fputs("\n\t", pf);
		uint64_t p = *(uint64_t *)&((char *)data)[i * datasize];
		p &= (1Ui64 << (datasize * 8)) - 1;
		int ret = fprintf(pf, format, p);
		for (int n = 0; n < blanksize - ret; n++) {
			fputc(' ', pf);
		}
	}
}

bool output(const char *filename, const unsigned int *freqlist, const unsigned long *beeptimelist, const unsigned long *sleeptimelist, size_t notecount) {
	unsigned int freqmap[MAX_FREQCOUNT];
	size_t freqcount = 0;

	unsigned long timemap[MAX_FREQCOUNT];
	size_t timecount = 0;

	FREQINDEX_TYPE *freqindex = (FREQINDEX_TYPE *)malloc(notecount * sizeof(FREQINDEX_TYPE));
	TIMEINDEX_TYPE *beeptimeindex = (TIMEINDEX_TYPE *)malloc(notecount * sizeof(TIMEINDEX_TYPE));
	TIMEINDEX_TYPE *sleeptimeindex = (TIMEINDEX_TYPE *)malloc(notecount * sizeof(TIMEINDEX_TYPE));
	
	if (freqindex == NULL || beeptimeindex == NULL || sleeptimeindex == NULL) {
		fprintf(stderr, "Run out of memory!\n");
		return false;
	}

	for (size_t i = 0; i < notecount; i++) {
		size_t j;
		//get freqmap
		for (j = 0; j < freqcount; j++) {
			if (freqmap[j] == freqlist[i]) break;
		}
		if (j == freqcount) {
			//not found
			if (j >= MAX_FREQCOUNT) {
				fprintf(stderr,
					"Exceeding maximum frequency count limit!\n"
					"You can fix this by editing \"FREQINDEX_TYPE\" in generator.c\n"
				);
				return false;
			}
			freqmap[j] = freqlist[i];
			freqcount = j + 1;
		}
		freqindex[i] = (FREQINDEX_TYPE)j;
		
		//get timemap - beep
		for (j = 0; j < timecount; j++) {
			if (timemap[j] == beeptimelist[i]) break;
		}
		if (j == timecount) {
			//not found
			if (j >= MAX_TIMECOUNT) {
				fprintf(stderr,
					"Exceeding maximum frequency count limit!\n"
					"You can fix this by editing \"TIMEINDEX_TYPE\" in generator.c\n"
				);//TODO
				return false;
			}
			timemap[j] = beeptimelist[i];
			timecount = j + 1;
		}
		beeptimeindex[i] = (TIMEINDEX_TYPE)j;

		//get timemap - sleep
		for (j = 0; j < timecount; j++) {
			if (timemap[j] == sleeptimelist[i]) break;
		}
		if (j == timecount) {
			//not found
			if (j >= MAX_TIMECOUNT) {
				fprintf(stderr,
					"Exceeding maximum frequency count limit!\n"
					"You can fix this by editing \"FREQINDEX_TYPE\" in generator.c\n"
				);
				return false;
			}
			timemap[j] = sleeptimelist[i];
			timecount = j + 1;
		}
		sleeptimeindex[i] = (TIMEINDEX_TYPE)j;
	}


	FILE *pf = fopen(filename, "w");
	if (pf == NULL) {
		fprintf(stderr, "Can't open output file \"%s\"!\n", filename);
		return false;
	}

	fprintf(pf,
		"/*\n"
		"  BeepArduino - %s\n"
		"\n"
		"  Generated by BeepArduino-Converter\n"
		"  Project website: <https://github.com/AlexGuo1998/BeepArduino>\n"
		"*/\n\n",
		filename
	);
	
	fprintf(pf, "#include <avr/pgmspace.h>\n\n");

	fprintf(pf, "#define PIN_BEEP 8\n\n");
	
	fprintf(pf, "const unsigned int freqmap[%zd] = {", freqcount);
	printNumbers(pf, "%u,", 6, 16, freqmap, freqcount, sizeof(*freqmap));
	fprintf(pf, "\n};\n");
	
	fprintf(pf, "const unsigned int timemap[%zd] = {", timecount);
	printNumbers(pf, "%u,", 6, 16, timemap, timecount, sizeof(*timemap));
	fprintf(pf, "\n};\n");

	fprintf(pf, "const unsigned " STR(TIMEINDEX_TYPE) " beeptime[%zd] PROGMEM = {", notecount);
	printNumbers(pf, "%lu,", 3, 32, beeptimeindex, notecount, sizeof(TIMEINDEX_TYPE));
	fprintf(pf, "\n};\n");

	fprintf(pf, "const unsigned " STR(TIMEINDEX_TYPE) " sleeptime[%zd] PROGMEM = {", notecount);
	printNumbers(pf, "%lu,", 3, 32, sleeptimeindex, notecount, sizeof(TIMEINDEX_TYPE));
	fprintf(pf, "\n};\n");

	fprintf(pf, "const unsigned " STR(FREQINDEX_TYPE) " notelist[%zd] PROGMEM = {", notecount);
	printNumbers(pf, "%hhu,", 3, 32, freqindex, notecount, sizeof(FREQINDEX_TYPE));
	fprintf(pf, "\n};\n");

	fprintf(pf, "\nvoid setup()" BRACKET_NEWLINE "{\n\n}\n\n");
	
	fprintf(pf,
		"void loop()" BRACKET_NEWLINE "{\n"
		"	for (int i = 0; i < sizeof(beeptime) / sizeof(beeptime[0]); i++) {\n"
		"		tone(PIN_BEEP, freqmap[pgm_read_byte_near(notelist + i)], timemap[pgm_read_byte_near(beeptime + i)]);\n"
		"		delay(timemap[pgm_read_byte_near(sleeptime + i)]);\n"
		"	}\n"
		"	while (true) delay(1000);\n"
		"}\n\n"
	);

	fclose(pf);

	return true;
}
